global using Microsoft.AspNetCore.Mvc;
global using TechMesh.Api.Controllers;
global using TechMesh.Auth.Application.DTOs.Auth.Request;
global using TechMesh.Auth.Application.Interfaces.Services.Infra;
global using TechMesh.Application.Results;
global using TechMesh.Auth.Application.DTOs.Auth.Response;
global using TechMesh.Api.Middlewares;
global using TechMesh.Auth.Infrastructure;
global using TechMesh.Auth.Application.Interfaces.Services.Auth;
